### ISSUE TITLE
This plugin does not work in Next 7.6

### ISSUE THREAD

**Issue by Tony-Tan** [theme-next/theme-next-fastclick#4]
I installed the plugin with
```
npm install theme-next/hexo-next-share --save
```
and added the following lines in configure file in next fold:
```
# Likely Share
# See: https://ilyabirman.net/projects/likely/, https://github.com/ilyabirman/Likely
# Likely supports four looks, nine social networks, any button text.
# You are free to modify the text value and order of any network.
likely:
  enable: true
  cdn:
    js: //cdn.jsdelivr.net/npm/ilyabirman-likely@2/release/likely.min.js
    css: //cdn.jsdelivr.net/npm/ilyabirman-likely@2/release/likely.min.css
  look: normal # available values: normal, light, small, big
  networks:
    twitter: Tweet
    facebook: Share
    linkedin: Link
    gplus: Plus
    vkontakte: Share
    odnoklassniki: Class
    telegram: Send
    whatsapp: Send
    pinterest: Pin
```

And generate and deployment with nothing happened:

my website: [https://brainbomb.org](https://brainbomb.org)
