### ISSUE TITLE
Make Wechat QRCode more comfortable in needmoreshare2

### ISSUE THREAD

**Issue by backrunner** [theme-next/theme-next-fastclick#7]
I set the style of wechat code like this:
```css
.need-share-button-opened img.need-share-wechat-code-image {
  width: 65% !important;
  margin: 0 auto !important;
  padding: 20px 0;
}
```

Before applied:
![image](https://user-images.githubusercontent.com/12205593/74168709-153dc900-4c65-11ea-8eff-9a385e903f47.png)

After applied: 
![image](https://user-images.githubusercontent.com/12205593/74168539-e162a380-4c64-11ea-8dda-0e699a51601f.png)

It's more comfortable. Hope it can be fixed in this project.
